# Generated by Django 4.0.5 on 2022-06-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('comentario', models.CharField(max_length=999)),
            ],
        ),
    ]
