# Generated by Django 4.0.5 on 2022-06-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kojo', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID producto')),
                ('nombreProducto', models.CharField(max_length=255, verbose_name='Nombre Producto')),
                ('stock', models.IntegerField(max_length=9, verbose_name='Stock')),
                ('precio', models.CharField(max_length=255, verbose_name='Precio')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
