# Generated by Django 4.0.5 on 2022-06-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kojo', '0005_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
