# Generated by Django 4.0.5 on 2022-06-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kojo', '0008_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmr_orden', models.BigIntegerField()),
                ('total', models.IntegerField()),
                ('fch_compra', models.CharField(max_length=10)),
                ('fch_entrega', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
