# Generated by Django 4.0.5 on 2022-06-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kojo', '0017_planta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planta',
            new_name='Plantita',
        ),
    ]
