# Generated by Django 4.0.5 on 2022-06-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kojo', '0022_rename_planta_plantas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plantas',
            new_name='Planta',
        ),
    ]
