# Generated by Django 4.0.5 on 2022-07-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kojo', '0024_planta_imagenplanta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaproducto',
            old_name='cantidad',
            new_name='cantidade',
        ),
    ]
