# Generated by Django 4.0.5 on 2022-07-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kojo', '0025_rename_cantidad_ventaproducto_cantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaproducto',
            old_name='cantidade',
            new_name='cantidad',
        ),
    ]
