# Generated by Django 4.0.5 on 2022-07-10 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kojo', '0026_rename_cantidade_ventaproducto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='idUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
