# Generated by Django 4.0.5 on 2022-07-11 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kojo', '0028_alter_venta_fch_compra_alter_venta_fch_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('idMiembro', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Miembro')),
                ('pertenece', models.BooleanField()),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
