# Generated by Django 4.0.5 on 2022-07-11 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kojo', '0031_ventaproducto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaproducto',
            old_name='ID',
            new_name='idUser',
        ),
    ]
