# Generated by Django 4.0.5 on 2022-07-11 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kojo', '0032_rename_id_ventaproducto_iduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaproducto',
            name='idUser',
        ),
        migrations.AlterField(
            model_name='venta',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kojo.venta'),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kojo.producto'),
        ),
    ]
