# Generated by Django 4.0.5 on 2022-07-11 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kojo', '0033_remove_ventaproducto_iduser_alter_venta_iduser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundacionMiembro',
            fields=[
                ('idMiembro', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Miem')),
                ('ID_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Fundacion',
        ),
    ]
