# Generated by Django 4.0.5 on 2022-07-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kojo', '0036_venta_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
    ]
